In [3]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [5]:
# create a simple dataframe
df=pd.DataFrame({
    'color':['red','blue','green','red','blue']
})

In [7]:
df.head()

   color
0    red
1   blue
2  green
3    red
4   blue

In [9]:
# create an instance of OneHotencoder
encoder=OneHotEncoder()

In [19]:
## perform fit and transform
encoded=encoder.fit_transform(df[['color']]).toarray()

In [23]:
import pandas as pd
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [25]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0

In [27]:
encoder.transform([['blue']]).toarray()

C:\Users\2309m\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [29]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3    red         0.0          0.0        1.0
4   blue         1.0          0.0        0.0

In [35]:
import seaborn as sns
df=sns.load_dataset('tips')

In [37]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [39]:
df['sex'].unique()

['Female', 'Male']
Categories (2, object): ['Male', 'Female']

In [41]:
encoded=encoder.fit_transform(df[['sex']]).toarray()

In [43]:
import pandas as pd
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [47]:
encoder_df

     sex_Female  sex_Male
0           1.0       0.0
1           0.0       1.0
2           0.0       1.0
3           0.0       1.0
4           1.0       0.0
..          ...       ...
239         0.0       1.0
240         1.0       0.0
241         0.0       1.0
242         0.0       1.0
243         1.0       0.0

[244 rows x 2 columns]

In [49]:
pd.concat([df,encoder_df],axis=1)

     total_bill   tip     sex smoker   day    time  size  sex_Female  sex_Male
0         16.99  1.01  Female     No   Sun  Dinner     2         1.0       0.0
1         10.34  1.66    Male     No   Sun  Dinner     3         0.0       1.0
2         21.01  3.50    Male     No   Sun  Dinner     3         0.0       1.0
3         23.68  3.31    Male     No   Sun  Dinner     2         0.0       1.0
4         24.59  3.61  Female     No   Sun  Dinner     4         1.0       0.0
..          ...   ...     ...    ...   ...     ...   ...         ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3         0.0       1.0
240       27.18  2.00  Female    Yes   Sat  Dinner     2         1.0       0.0
241       22.67  2.00    Male    Yes   Sat  Dinner     2         0.0       1.0
242       17.82  1.75    Male     No   Sat  Dinner     2         0.0       1.0
243       18.78  3.00  Female     No  Thur  Dinner     2         1.0       0.0

[244 rows x 9 columns]

In [51]:
df['time'].unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [53]:
encoded=encoder.fit_transform(df[['time']]).toarray()

In [55]:
import pandas as pd
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [57]:
encoder_df

     time_Dinner  time_Lunch
0            1.0         0.0
1            1.0         0.0
2            1.0         0.0
3            1.0         0.0
4            1.0         0.0
..           ...         ...
239          1.0         0.0
240          1.0         0.0
241          1.0         0.0
242          1.0         0.0
243          1.0         0.0

[244 rows x 2 columns]