In [1]:
import pandas as pd

In [5]:
df=pd.DataFrame({
    'color':['red','blue','green','green','red']
})

In [7]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [9]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [15]:
lbl_encoder.fit_transform(df[['color']])

C:\Users\2309m\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2])

In [19]:
lbl_encoder.transform([['blue']])

C:\Users\2309m\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [21]:
#while assigning unique labels to red blue greeen
# red has got 2 so the model,when this data will come it will start thinking rd may have 
#a higher value when compared to blue or green so this should not happen because it is nominal value 
# but yes, if there is a situation where you need to assign rans to this particular vaues to this categories 
#using ordinal encoding

# Ordinal Encoding

In [25]:
# 1. high School :1
# 2. College :2
# 3. Graduate:3
# 4. Post-graduate:4

In [27]:
## Ordinal Encoding
from sklearn.preprocessing import OrdinalEncoder

In [29]:
df=pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [31]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [33]:
## create an instance of OrdinalEncoder and the fit_transform 

encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [35]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [39]:
encoder.transform([['small']])

C:\Users\2309m\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

# Target Guided Ordinal Encoding 
we replace each category in the categorical variable with a numerical variable with a numerical value based 
on mean or median of the target variable for that category .

In [42]:
import pandas as pd
# create a sample datframe with a categorical variable and a target variable

df=pd.DataFrame({
    'city':['New York','London','Paris','Tokyo','New York','Paris'],
    'price':[200,150,300,250,180,320]
})

In [44]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [48]:
mean_price=df.groupby('city')['price'].mean().to_dict()

In [50]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [52]:
df['city_encoded']=df['city'].map(mean_price)

In [54]:
df

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0

In [58]:
df[['price','city_encoded']]

   price  city_encoded
0    200         190.0
1    150         150.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0

In [60]:
import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]