 # Pandas-DataFrame And Series
- Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning.
- It provides two primary data structures: Series and DataFrame.
-  A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [98]:
import pandas as pd

In [100]:
## Series
''' A Pandas Series is a one-dimensional array-like object that can hold any data type. 
It is similar to a column in a table. '''

import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print("Series \n",series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [102]:
## Create a series from dictionary 
data = {'a' :1 ,'b':2 , 'c':3}
series_dic = pd.Series(data)
print(series_dic)

a    1
b    2
c    3
dtype: int64

In [104]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data , index)

a    10
b    20
c    30
dtype: int64

In [106]:
## Dataframe 
## Create a DataFrame from a dictionary off list 

data = {
    'Name':['Mayuri' , 'Gouri' , 'Shrushti'],
    'Age':[21,19,25],
    'city':['Solapur','Pune','Nagpur']
}
df = pd.DataFrame(data)
print(df)
print(type(df))

       Name  Age     city
0    Mayuri   21  Solapur
1     Gouri   19     Pune
2  Shrushti   25   Nagpur
<class 'pandas.core.frame.DataFrame'>

In [108]:
## Create a Data frame From a List of Dictionaries

data=[
    {'Name':'Mayuri','Age':20,'City':'Solapur'},
    {'Name':'SOham','Age':14,'City':'Delhi'},
    {'Name':'Pranav','Age':19,'City':'Pune'},
    {'Name':'Shrushti','Age':19,'City':'Nagapur'}
    
]
df=pd.DataFrame(data)
print(df)
print(type(df))

       Name  Age     City
0    Mayuri   20  Solapur
1     SOham   14    Delhi
2    Pranav   19     Pune
3  Shrushti   19  Nagapur
<class 'pandas.core.frame.DataFrame'>

In [110]:
print(df['Name'])
type(df['Name'])

0      Mayuri
1       SOham
2      Pranav
3    Shrushti
Name: Name, dtype: object

pandas.core.series.Series

In [112]:
df.loc[0]  # 0th row

Name     Mayuri
Age          20
City    Solapur
Name: 0, dtype: object

In [114]:
df.loc[0][0]

C:\Users\2309m\AppData\Local\Temp\ipykernel_32728\2527876973.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'Mayuri'

In [116]:
df.iloc[0]

Name     Mayuri
Age          20
City    Solapur
Name: 0, dtype: object

In [118]:
df

       Name  Age     City
0    Mayuri   20  Solapur
1     SOham   14    Delhi
2    Pranav   19     Pune
3  Shrushti   19  Nagapur

In [120]:
## Accessing a Specified element 

print(df.at[1,'Age'])
print(df.at[2,'Age'])

14
19

In [122]:
print(df.at[1,'Name'])

SOham

In [124]:
## Accessing a speciefied element using iat 
df.iat[2,2]  # row 2 column 2

'Pune'

In [126]:
### Data Manipulation with Dataframe
df

       Name  Age     City
0    Mayuri   20  Solapur
1     SOham   14    Delhi
2    Pranav   19     Pune
3  Shrushti   19  Nagapur

In [128]:
df['Salary'] = [50000,60000,70000,80000]
df

       Name  Age     City  Salary
0    Mayuri   20  Solapur   50000
1     SOham   14    Delhi   60000
2    Pranav   19     Pune   70000
3  Shrushti   19  Nagapur   80000

In [130]:
# Remove a column 
df.drop('Salary',axis=1)

       Name  Age     City
0    Mayuri   20  Solapur
1     SOham   14    Delhi
2    Pranav   19     Pune
3  Shrushti   19  Nagapur

In [132]:
df
# even after dropping still present

       Name  Age     City  Salary
0    Mayuri   20  Solapur   50000
1     SOham   14    Delhi   60000
2    Pranav   19     Pune   70000
3  Shrushti   19  Nagapur   80000

In [134]:
# Remove a column 
df.drop('Salary',axis=1,inplace=True)

In [140]:
## Add age to the column 
df['Age'] = df['Age'] + 1
df

       Name  Age     City
0    Mayuri   21  Solapur
1     SOham   15    Delhi
2    Pranav   20     Pune
3  Shrushti   20  Nagapur

In [146]:
df.drop(0,inplace=True)

In [148]:
df

       Name  Age     City
1     SOham   15    Delhi
2    Pranav   20     Pune
3  Shrushti   20  Nagapur

In [150]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [152]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

# Describe the DataFrame
print("Statistical summary:\n", df.describe())

Data types:
 Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object
Statistical summary:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [154]:

df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000